BEGIN;

ALTER TABLE app.tenants
  ADD COLUMN IF NOT EXISTS sftp_username TEXT,
  ADD COLUMN IF NOT EXISTS sftp_home_uri TEXT,
  ADD COLUMN IF NOT EXISTS sftp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sftp_provisioned_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS sftp_last_error_code TEXT,
  ADD COLUMN IF NOT EXISTS sftp_last_error_at TIMESTAMPTZ;

COMMIT;
